version: "3.8"

services:
  frontend:
    build: ./core/frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

  restaurant-service:
    build: ./core/backend/restaurant
    ports:
      - "3001:3000"
    networks:
      - app-network

  menu-service:
    build: ./core/backend/menu
    ports:
      - "3002:3000"
    networks:
      - app-network

  order-service:
    build: ./core/backend/order
    ports:
      - "3003:3000"
    networks:
      - app-network

  delivery-service:
    build: ./core/backend/delivery
    ports:
      - "3004:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - restaurant-service
      - menu-service
      - order-service
      - delivery-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
